name: release
on:
  release:
    types:
    - published
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: |
        sudo python3 -m pip install git+https://github.com/luarocks/hererocks
        sudo hererocks -l 5.1 -r 3.8.0 /usr/local
        sudo luarocks install dkjson
    - name: luarocks upload
      run: |
        v=${{ github.event.release.tag_name }}
        v=${v:1}
        key=${{ secrets.LUAROCKS_API_KEY }}
        spec=wowcig-${v}-0.rockspec
        sed s/scm/"${v}"/g < wowcig-scm-0.rockspec > "${spec}"
        luarocks upload --skip-pack --force --temp-key "${key}" "${spec}"
