name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install cargo libzip-dev
        sudo cargo install --root=/usr/local --version=0.12.4 stylua
        sudo python3 -m pip install git+https://github.com/luarocks/hererocks
        sudo hererocks -l 5.1 -r 3.8.0 /usr/local
        sudo luarocks install luacheck
        sudo luarocks install --only-deps wowcig
    - uses: pre-commit/action@v2.0.3
